name: Pre-commit QA

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Cache Pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-
    - uses: pre-commit/action@v3.0.0