name: Pre-commit QA

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      # Install pre-commit package
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      # Step to fix 'python_venv' language to 'python' in .pre-commit-hooks.yaml
      - name: Fix 'python_venv' language to 'python' in .pre-commit-hooks.yaml
        run: |
          echo "Fixing pre-commit hook language..."
          # Modify the cached pre-commit-hooks.yaml files before installation
          find ~/.cache/pre-commit/ -type f -name '.pre-commit-hooks.yaml' -exec sed -i 's/python_venv/python/g' {} +

      # Install pre-commit hooks after fixing language key
      - name: Install pre-commit hooks
        run: pre-commit install

      # Run pre-commit action
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
        with:
          all_files: true
